version: '3.7'

services:
    postgres:
        image: clkao/postgres-plv8
        container_name: esecomm-postgres
        environment:
            POSTGRES_PASSWORD: Pass@word
        ports:
            - "5432:5432"
        networks:
            - esecomm_pg_network

    pgadmin:
        image: dpage/pgadmin4
        container_name: esecomm-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - esecomm_pg_network

networks:
    default:
        name: esecomm_network
    esecomm_pg_network:
        driver: bridge
