version: '3'
services:
    postgresql:
        image: "clkao/postgres-plv8:latest"
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_DATABASE=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Pass@word123

    pgadmin4:
        image: dpage/pgadmin4:latest
        ports:
            - 81:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
