version: '3.7'

services:
    postgres:
        image: clkao/postgres-plv8
        container_name: ecomm_postgres
        environment:
            POSTGRES_PASSWORD: Pass@word123
        ports:
            - "5432:5432"
        networks:
            - ecomm_pg_network

    pgadmin:
        image: dpage/pgadmin4
        container_name: ecomm_pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - ecomm_pg_network

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: ecomm_sqlserver
        environment:
            - "ACCEPT_EULA=Y"
            - "SA_PASSWORD=Pass@word456"
            - "MSSQL_PID=Developer"
        ports:
            - "1433:1433"
        networks:
            - ecomm_pg_network

networks:
    default:
        name: ecomm_network
    ecomm_pg_network:
        driver: bridge
