services:

    esdb:
        image: eventstore/eventstore:24.2.0-bookworm-slim
        container_name: ecomm_esdb
        ports:
            - '2113:2113'
            - '1113:1113'
        environment:
            EVENTSTORE_INSECURE: 'true'
            EVENTSTORE_CLUSTER_SIZE: 1
            EVENTSTORE_RUN_PROJECTIONS: all
            EVENTSTORE_START_STANDARD_PROJECTIONS: 'true'
            EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: 'true'
        networks:
            - ecomm_esdb_network

    zipkin:
        image: openzipkin/zipkin
        container_name: ecomm_zipkin
        ports:
            - "9411:9411"

    seq:
        image: datalust/seq:latest
        container_name: ecomm_seq
        environment:
            - ACCEPT_EULA=Y
        ports:
            - "5341:80"

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: ecomm_sqlserver
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStrong_Password123#
            - MSSQL_PID=Developer
        networks:
            - ecomm_sql_network

    postgres:
        image: postgres:latest
        container_name: ecomm_postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=Password123!
        networks:
            - ecomm_pg_network

    pgadmin:
        image: dpage/pgadmin4
        container_name: ecomm_pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - ecomm_pg_network

#    catalog.api:
#        image: catalog.api
#        container_name: ecomm_catalog_api
#        ports:
#            - "5253:80"
#        build:
#            context: .
#            dockerfile: src/Catalog/Catalog.Api/Dockerfile

#    inventory.api:
#        image: inventory.api
#        container_name: ecomm_inventory_api
#        ports:
#            - "5155:80"
#        build:
#            context: .
#            dockerfile: src/Inventory/Inventory.Api/Dockerfile

#    pricing.api:
#        image: pricing.api
#        container_name: ecomm_pricing_api
#        ports:
#            - "5219:80"
#        build:
#            context: .
#            dockerfile: src/Pricing/Pricing.Api/Dockerfile

#    legacy.api:
#        image: legacy.api
#        container_name: ecomm_legacy_api
#        ports:
#            - "5255:80"
#        build:
#            context: .
#            dockerfile: src/Legacy/Legacy.Api/Dockerfile

networks:
    default:
        name: ecomm_network
    ecomm_esdb_network:
        driver: bridge
    ecomm_sql_network:
        driver: bridge
    ecomm_pg_network:
        driver: bridge
