# curl -X 'GET'
#  'http://localhost:5252/offers/0190421a-1466-4f1b-8261-a22a528aadae'
#  -H 'accept: text/plain'
GET http://localhost:5252/offers/0190421a-1466-4f1b-8261-a22a528aadae
accept: text/plain

###

# curl -X 'POST'
#  'http://localhost:5252/offer/draft'
#  -H 'accept: text/plain'
#  -H 'Content-Type: application/json'
#  -d '{
#  "sku": "36606-001",
#  "createdBy": "erik"
#}'
POST http://localhost:5252/offer/draft
accept: text/plain
Content-Type: application/json

{
    "sku": "36606-001",
    "createdBy": "erik"
}

###

# curl -X 'POST'
#  'http://localhost:5252/offer/activate'
#  -H 'accept: text/plain'
#  -H 'Content-Type: application/json'
#  -d '{
#  "offerId": "0190421a-1466-4f1b-8261-a22a528aada",
#  "activatedBy": "erik"
#}'
POST http://localhost:5252/offer/activate
accept: text/plain
Content-Type: application/json

{
    "offerId": "0190421a-1466-4f1b-8261-a22a528aadae",
    "activatedBy": "erik"
}

###

